remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Privacy Policy - Image Resizer & Compressor
description: Privacy policy for the Image Resizer & Compressor Android app
show_downloads: false
